### ISSUE TITLE
Was 'unlink' intentionally removed?

### ISSUE THREAD

**Issue by barn3y** [NodeRedis/redis-commands#17]
https://github.com/NodeRedis/redis-commands/commit/8bd7918a5c970d1308e083c2056b1ec39c780425#diff-e2571e1121887e3a7e1bf9d686e0ffceL1540

The `unlink` command was removed recently, was this intentional?

Edit: it looks like `module` and `memory` were also removed... were the commands rebuilt from a version of redis prior to 4?

**Comment by BridgeAR** [comment]
Absolutely not. I used the wrong Redis version when updating. Fixed in v.1.3.5.

**Comment by BridgeAR** [comment]
Thanks a lot for reporting it.

**Comment by barn3y** [comment]
Thanks for fixing!
