### ISSUE TITLE
can I get server current time using node.js ?

### ISSUE THREAD

**Issue by MarwaAbed** [NodeRedis/redis-commands#24]
Hi all,
please, I need to get the Redis server insert time put I didn't find a way to do that the only one that was useful is to me is to insert the current Redis server time that found in [this site](https://redis.io/commands/time), did anyone know how to use time command with node.js have a way to get the insert time?

**Comment by stockholmux** [comment]
@MarwaAbed `TIME` is [supported](https://github.com/NodeRedis/redis-commands/blob/master/commands.json#L1547). In [node_redis](https://github.com/NodeRedis/node_redis) it should be `client.time(function(err,resp) { ... })`.

**Comment by MarwaAbed** [comment]
thank you Mr. Kyle J. Davis
