### ISSUE TITLE
Publish a new version on NPM for Redis 5.0 commands please

### ISSUE THREAD

**Issue by lakano** [NodeRedis/redis-commands#25]
Hi,

We would like to uses Redis 5.0 commands ( the final release is planned the 17th october, in 9 days). The current version 1.3.5 doesn't includes the last changes of your master branch, I don't see in the commands.json the XADD or BZPOPMIN/MAX commands.

I've [opened an issue on ioredis](https://github.com/luin/ioredis/issues/716) but this seems to be a finally related to this package, could you please push a new version ? :)

**Comment by luin** [comment]
Published v1.4.0.

**Comment by xprudhomme** [comment]
Hello @luin , is it possible to update the commands list with the latests/newest additions, such as the [LPOS command](https://redis.io/commands/lpos) (Available since 6.0.6)?

Cheers

**Comment by luin** [comment]
@xprudhomme Updated in v1.6.0
