### ISSUE TITLE
Redis 6.2 command changes

### ISSUE THREAD

**Issue by shaharmor** [NodeRedis/redis-commands#40]
Hi,

According to the [Redis 6.2 release notes](https://raw.githubusercontent.com/redis/redis/6.2/00-RELEASENOTES), several commands have changed in one way or another.

Can we get this module to update according to the new changes?

Example:

`LPOP` now accepts a `COUNT` optional parameter which changes the return value type

**Comment by luin** [comment]
Hey Shahar,

I believe commands introduced in 6.2 are already there with v1.7.0, or did I miss something?

**Comment by shaharmor** [comment]
My bad.

The bug is actually in missing types in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ioredis/index.d.ts

Keep up the good work!
